### ISSUE TITLE
Bots can receive karma

### ISSUE THREAD

**Issue by xLive** [qaisjp/iggystats#7]
I think bots should not get karma 

![image](https://user-images.githubusercontent.com/30420446/75540616-6acbf100-5a2d-11ea-8a16-10b52086151e.png)

**Comment by qaisjp** [comment]
thanks for the report.

just don't use karma on bots if you think it's pointless. the karma feature is for fun, and just for fun

closing this because if someone wants to upvote or downvote a bot as a joke, that's fine
